CREATE OR REPLACE EDITIONABLE TRIGGER "STA_SYSTEM_PARAMETER_IOIUD" 
  INSTEAD OF INSERT OR UPDATE OR DELETE
  ON "STA_SYSTEM_PARAMETER_DML_V"
  FOR EACH ROW
  /*
  This is the instead of trigger for the DML view of the table "STA_SYSTEM_PARAMETER".
  - Generator:         OM_TAPIGEN
  - Generator version: 0.6.3
  - Generator action:  COMPILE_API
  - Generated at:      2024-05-01 03:06:25
  - Generated by:      PNL14U85
  */
BEGIN
  IF INSERTING THEN
    "STA_SYSTEM_PARAMETER_API".create_row (
      p_id        => :new."ID" /*PK*/ /*GENERATED BY DEFAULT ON NULL AS IDENTITY*/,
      p_parameter => :new."PARAMETER",
      p_value     => :new."VALUE" );
  ELSIF UPDATING THEN
    "STA_SYSTEM_PARAMETER_API".update_row (
      p_id        => :new."ID" /*PK*/,
      p_parameter => :new."PARAMETER",
      p_value     => :new."VALUE" );
  ELSIF DELETING THEN
    raise_application_error (-20000, 'Deletion of a row is not allowed.');
  END IF;
END "STA_SYSTEM_PARAMETER_IOIUD";
/
