create table sta_student_remark(
    id     number generated by default on null as identity,
    usr_id number         not null,
    remark varchar2(4000) not null,
    constraint sta_sdnt_rmk_pk primary key(id),
    constraint sta_sdnt_rmk_usr_fk foreign key(usr_id)references sta_user
);