create table sta_announcement
(
    id            number generated by default on null as identity
        constraint sta_anmt_pk
            primary key,
    title         varchar2(255) not null,
    message       clob          not null,
    priority      varchar2(20)  not null
        constraint sta_anmt_chk2
            check (priority in ('High', 'Medium', 'Low')),
    created_by    varchar2(320),
    created_date  date,
    modified_by   varchar2(320),
    modified_date date
)
/


