create table sta_student_test
(
    id     number generated by default on null as identity
        constraint sta_sdnt_tst_pk
            primary key,
    usr_id number      not null
        constraint sta_sdnt_tst_usr_fk
            references sta_user,
    tst_id number      not null
        constraint sta_sdnt_tst_tst_fk
            references sta_test,
    result varchar2(2) not null
)
/

