create table sta_course_teacher
(
    id      number generated by default on null as identity
        constraint sta_crse_tchr_pk
            primary key,
    crse_id number not null
        constraint sta_crse_tchr_crse_fk
            references sta_course,
    usr_id  number not null
        constraint sta_crse_tchr_usr_fk
            references sta_user
)
/

