create table sta_semester
(
    id         number generated by default on null as identity
        constraint sta_smsr_pk
            primary key,
    name       varchar2(40) not null,
    schoolyear varchar2(9)  not null,
    start_date date         not null,
    end_date   date         not null,
    active_ind boolean      not null,
    constraint sta_smsr_uk1
        unique (start_date, end_date),
    constraint sta_smsr_chk1
        check (start_date < end_date)
)
/

