create table sta_course
(
    id          number generated by default on null as identity
        constraint sta_crse_pk
            primary key,
    name        varchar2(40) not null,
    description varchar2(200)
)
/

