create table sta_announcement
(
    id         number generated by default on null as identity
        constraint sta_anmt_pk
            primary key,
    title      varchar2(255) not null,
    message    clob          not null,
    status     varchar2(20)  not null
        constraint sta_anmt_chk1
            check (status in ('Active', 'Expired', 'Draft')),
    priority   varchar2(20)  not null
        constraint sta_anmt_chk2
            check (priority in ('High', 'Medium', 'Low'))
)
/

