create table sta_course_grade
(
    id      number generated by default on null as identity
        constraint sta_crse_grde_pk
            primary key,
    crse_id number not null
        constraint sta_crse_grde_crse_fk
            references sta_course,
    grde_id number not null
        constraint sta_crse_grde_grde_fk
            references sta_grade,
    constraint sta_crse_grde_uk1
        unique (crse_id, grde_id)
)
/

