create table sta_authorization_privilege
(
    id      number generated by default on null as identity
        constraint sta_auth_pve_pk
            primary key,
    auth_id number not null
        constraint sta_auth_pve_auth_fk
            references sta_authorization,
    pve_id  number not null
        constraint sta_auth_pve_pve_fk
            references sta_privilege
)
/

alter table sta_authorization_privilege add constraint sta_auth_pve_uk1 unique(auth_id, pve_id);
