create table sta.sta_event
(
    id         number generated by default on null as identity
        constraint sta_evnt_pk
            primary key,
    name       varchar2(80) not null,
    start_date date         not null,
    end_date   date
);
