create table sta_grade
(
    id             number      default "STA"."ISEQ$$_76841".nextval generated by default on null as identity
		constraint STA_GRDE_PK
			primary key,
    name           varchar2(40)            not null,
    description    varchar2(200),
    exam_grade_flg varchar2(1) default 'N' not null
        constraint sta_grde_chk1
            check (exam_grade_flg in ('Y', 'N'))
)
;
