create table sta_authorization
(
    id                  number  generated by default on null as identity
        constraint STA_AUTH_PK
        primary key,
    name                varchar2(100) not null,
    apex_component_name varchar2(200),
    apex_page           number,
    apex_component_type varchar2(200) not null,
    row_operation       varchar2(1),
    read_only           boolean default true,
    constraint sta_auth_uk1
        unique (apex_component_name, apex_page, read_only, row_operation)
)
/
