create table sta.sta_system_parameter
(
    id        number      default "STA"."ISEQ$$_76866".nextval generated by default on null as identity
		constraint STA_SYPA_PK
			primary key,
    parameter varchar2(80)            not null,
    value     varchar2(100)           not null,
    show_ind  varchar2(1) default 'N' not null
        constraint sta_sypa_chk1
            check (show_ind in ('Y', 'N'))
)
/


