create table sta_privilege
(
    id          number generated by default on null as identity
        constraint sta_pve_pk
            primary key,
    name        varchar2(80) not null,
    description varchar2(200)
)
/

