create table sta_course_class_teacher
(
    id         number generated by default on null as identity,
    crse_id number not null,
    clss_id    number not null,
    usr_id     number not null,
    constraint sta_crse_clss_tchr_pk primary key (id),
    constraint sta_crse_clss_tchr_crse_fk foreign key(crse_id) references sta_course,
    constraint sta_crse_clss_tchr_clss_fk foreign key(clss_id) references sta_class,
    constraint sta_crse_clss_tchr_usr_fk  foreign key(usr_id) references sta_user,
    constraint sta_crse_clss_tchr_uk1 unique (crse_id, clss_id, usr_id)
);
