 create table sta_teacher_audit (
  id                         number generated by default on null as identity
, voornaam                   varchar2(4000)
, achternaam                 varchar2(4000)
, hoofd_adres                varchar2(4000)
, alternatief_adres          varchar2(4000)
, hoofd_telefoonnummer       varchar2(4000)
, alternatief_telefoonnummer varchar2(4000)
, email                      varchar2(4000)
, is_admin                   varchar2(4000)
, password                   varchar2(4000)
, courses                    varchar2(4000)
, actie                      varchar2(20)
, actie_datum                date
, gedaan_door                varchar2(4000)
 );



