--sta_role.sql
-- create table sta_role(
--     id number generated by default on null as identity,
--     name varchar2(40) not null,
--     system_name varchar2(40),
--     system_name2 varchar2(40),
--     constraint sta_rle_pk primary key(id),
--     constraint sta_rle_uk1 unique(name),
--     constraint sta_role_uk2 unique (system_name)
-- );
-- alter table sta_role add system_name varchar2(40);
-- alter table sta_role add constraint sta_role_uk2 unique (system_name);

alter table sta_role add system_name2 varchar2(40);
