CREATE OR REPLACE FORCE EDITIONABLE VIEW "STA_SYSTEM_PARAMETER_DML_V" 
 ( "ID", "PARAMETER", "VALUE"
  )  AS 
  SELECT "ID" /*PK*/,
      "PARAMETER",
      "VALUE"
  FROM "STA_SYSTEM_PARAMETER"
 
  /*
  This is the DML view for the table "STA_SYSTEM_PARAMETER".
  - Generator:         OM_TAPIGEN
  - Generator version: 0.6.3
  - Generator action:  COMPILE_API
  - Generated at:      2024-05-01 03:06:25
  - Generated by:      PNL14U85
  */
  